redis:
  jedis:
    database: 1
    host: 127.0.0.1
    password: 123456
    pool:
      max-active: 200
      max-idle: 8
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 6000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  servlet:
    context-path: /userApi
  port: 8080

spring:

  application:
    name: user-service
  mvc:
    view:
      prefix: /pages/
      suffix: .html
  http:
    encoding:
      charset: utf-8
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zte_attendance?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
      type: com.zaxxer.hikari.HikariDataSource

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/*/*.xml
  type-aliases-package: com.zzxmh.userservice

logging:
  file: user-service.log
  path: /var/log/
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'

